name: datasim

channels:
  - conda-forge

dependencies:
  - python>=3.12
  - pytest>=8.3.4
  - pytest-md>=0.2.0
  - numpy>=2.2.3
  - pandas>=2.2.3
  # - dash>=3.0.1
  # - dash-bootstrap-components>=2.0.0
  - streamlit>=1.43.2
  - plotly>=5.24.1
  - scipy>=1.15.1
  - psutil>=5.9.0
