name: Code quality & Unit tests

on:
  push:
    branches:
    - main

jobs:
  style-type-test-cov:
    uses: lpenz/ghworkflow-python/.github/workflows/python.yml@v0.8.1
    with:
      docs: false
      coveralls: true
