name: Python Test Typing and PyTest Unit Tests with Conda

on:
  push:
    branches:
    - main

jobs:
  env:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        
  lint:
    needs: env
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
  type:
    needs: env
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - name: Test strict typing with pyright
      uses: jakebailey/pyright-action@v2
      
  test:
    needs: env
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
