name: Code quality & Unit tests

on:
  push:
    branches:
    - main

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Lint with flake8
      uses: py-actions/flake8@v2
      with:
        max-line-length: 120
    - name: Test strict typing with pyright
      run: python -m pyright --project pyrightconfig.json
    - name: Test docstrings according to PEP257
      run: python -m pydocstyle --add-ignore=D100 --add-select=D212 ./datasim
    - name: Set timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: 'Europe/Amsterdam'
    - name: Run pytest
      uses: pavelzw/pytest-action@v2
      with:
        emoji: false
        verbose: false
        job-summary: true
        custom-arguments: '--cov-config=.coveragerc --cov=datasim/'
    - name: Coveralls
      uses: coverallsapp/github-action@v2
