name: Python Linting, Typing and PyTest Unit Tests with Conda

on:
  push:
    branches:
    - main

jobs:
  env:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base

  lint:
    needs: env
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - name: Lint with flake8
      uses: py-actions/flake8@v2

  type:
    needs: env
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - name: Test strict typing with pyright
      uses: jakebailey/pyright-action@v2

  test:
    needs: env
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - name: Set timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: 'Europe/Amsterdam'
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -vv
